# Generated by Django 4.2.8 on 2023-12-04 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Todo',
        ),
    ]
