# Generated by Django 4.2.8 on 2023-12-04 23:51

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('todo', 'Todo')
    Student(name="Joe Silver", email="joe@email.com", phone="00000000").save()


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
