# Generated by Django 4.2.8 on 2023-12-04 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_student_todo'),
        ('todo', '0003_todo'),
    ]

    operations = [
    ]
